#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -f "$DIR/.lib/saxon.jar" ]; then
  echo "Saxon is Already downloaded"
else 
  mkdir -p $DIR/.lib
  curl http://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/9.5.1-3/Saxon-HE-9.5.1-3.jar > $DIR/.lib/saxon.jar
fi
